# Workflow to run a Matlab script on GitHub-Hosted Linux, Windows and macOS runners
# See: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners

# Workflow name
name: Run Matlab script on GitHub-hosted runners
# Name for each run
run-name: "${{ github.event.head_commit.message }}"

# Parameters
env:
  MATLAB_VER: R2021b # Oldest "b" release available for Windows

# When the workflow will run
on:
  # Run on Push to 'master' or 'main' branch
  push:
    branches:
      - master
      - main
  # Run manually from GitHub Actions tab
  workflow_dispatch:

jobs:
  # Ubuntu job
  Run-Ubuntu:
    name: Run on Linux (Ubuntu 20.04)
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Set up Matlab
        uses: matlab-actions/setup-matlab@v1
        with:
          release: ${{ env.MATLAB_VER }}
      - name: Run script
        uses: matlab-actions/run-command@v1
        with:
          command: wonder_script
      - name: Print PWD
        run: pwd
      - name: Print results
        run: cat ./data/results.txt

  # Windows job
  Run-Windows:
    name: Run on Windows (Server 2019)
    runs-on: windows-2019
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Set up Matlab
        uses: matlab-actions/setup-matlab@v1
        with:
          release: ${{ env.MATLAB_VER }}
      - name: Run script
        uses: matlab-actions/run-command@v1
        with:
          command: wonder_script
      - name: Print PWD
        run: pwd
      - name: Print results
        run: type .\data\results.txt

  # macOS job
  Run-MacOS:
    name: Run on macOS (12 Monterey)
    runs-on: macos-12
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Set up Matlab
        uses: matlab-actions/setup-matlab@v1
        with:
          release: ${{ env.MATLAB_VER }}
      - name: Run script
        uses: matlab-actions/run-command@v1
        with:
          command: wonder_script
      - name: Print PWD
        run: pwd
      - name: Print results
        run: cat ./data/results.txt
